# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '2coderMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SDWebImage', '~> 5.12'
  use_frameworks!

  # Pods for 2coderMovies

end
